/**
 * Service worker: does the actual work.
 *
 * Flow:
 *   popup / keyboard shortcut
 *     -> inject a function into the YouTube tab to read the player data
 *     -> fetch the caption track (or scrape the transcript panel as a fallback)
 *     -> build Markdown
 *     -> chrome.downloads saves it as "<video title>.md"
 */

// Downloads land in <Downloads>/YouTube Transcripts/. Set to '' to use the
// Downloads root instead.
const DOWNLOAD_SUBFOLDER = 'YouTube Transcripts';

// A paragraph/timestamp line is closed once it passes either of these.
// 30s / 400 chars keeps lines readable without turning into a wall of text.
const CHUNK_MAX_SECONDS = 30;
const CHUNK_MAX_CHARS = 400;

// Caption times only ever move forward. A jump backwards larger than this means
// the transcript started over rather than a caption arriving slightly late.
const RESTART_BACKWARD_SECONDS = 5;

/* ------------------------------------------------------------------ */
/* Functions injected into the YouTube page                            */
/* ------------------------------------------------------------------ */

/**
 * Runs in the page's MAIN world so it can see YouTube's own JS objects.
 * Returns the video title/author plus the list of available caption tracks.
 */
function pageReadVideoInfo() {
  let playerResponse = null;

  // The player object always knows the CURRENT video, even after YouTube's
  // in-page navigation. ytInitialPlayerResponse can be stale, so it is a fallback.
  const player = document.getElementById('movie_player');
  if (player && typeof player.getPlayerResponse === 'function') {
    playerResponse = player.getPlayerResponse();
  }
  if (!playerResponse) {
    playerResponse = window.ytInitialPlayerResponse || null;
  }
  if (!playerResponse) {
    return { ok: false, error: 'Could not read the YouTube player data on this page.' };
  }

  const details = playerResponse.videoDetails || {};
  const captions = playerResponse.captions || {};
  const trackList = captions.playerCaptionsTracklistRenderer || {};
  const rawTracks = trackList.captionTracks || [];

  const tracks = rawTracks.map((track) => {
    let label = track.languageCode || 'unknown';
    if (track.name && track.name.simpleText) {
      label = track.name.simpleText;
    } else if (track.name && track.name.runs && track.name.runs.length > 0) {
      label = track.name.runs[0].text;
    }
    return {
      label: label,
      languageCode: track.languageCode || '',
      isAutoGenerated: track.kind === 'asr',
      url: track.baseUrl
    };
  });

  return {
    ok: true,
    title: details.title || document.title.replace(/ - YouTube$/, ''),
    author: details.author || '',
    videoId: details.videoId || '',
    lengthSeconds: Number(details.lengthSeconds || 0),
    pageUrl: location.href.split('&')[0],
    tracks: tracks
  };
}

/**
 * Runs in the page's MAIN world so the request carries YouTube's own origin
 * and cookies. Downloads one caption track and turns it into segments.
 * Returns { ok: true, segments: [{ start: seconds, text }] }.
 */
async function pageFetchCaptionTrack(baseUrl) {
  try {
    const url = new URL(baseUrl);
    url.searchParams.set('fmt', 'json3'); // JSON is easier to parse than the default XML
    const response = await fetch(url.toString(), { credentials: 'include' });
    if (!response.ok) {
      return { ok: false, error: 'Caption download failed (HTTP ' + response.status + ').' };
    }

    const data = await response.json();
    const events = data.events || [];
    const segments = [];

    for (const event of events) {
      if (!event.segs) continue;

      let text = '';
      for (const piece of event.segs) {
        text += piece.utf8 || '';
      }
      text = text.replace(/\s+/g, ' ').trim();
      if (!text) continue;

      segments.push({ start: (event.tStartMs || 0) / 1000, text: text });
    }

    if (segments.length === 0) {
      return { ok: false, error: 'The caption track was empty.' };
    }
    return { ok: true, segments: segments, source: 'captions' };
  } catch (error) {
    return { ok: false, error: 'Caption download failed: ' + error.message };
  }
}

/**
 * Fallback that runs in the isolated world (DOM only): opens YouTube's own
 * "Show transcript" panel and reads the segments out of it. Slower and more
 * fragile than the caption API, but it works when the API refuses.
 */
async function pageScrapeTranscriptPanel() {
  const sleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));

  function parseTimestamp(stamp) {
    const parts = stamp.split(':').map((part) => Number(part));
    if (parts.some((part) => Number.isNaN(part))) return 0;
    let seconds = 0;
    for (const part of parts) {
      seconds = seconds * 60 + part;
    }
    return seconds;
  }

  /**
   * A watch page can hold more than one transcript panel at a time: YouTube
   * leaves the previous video's engagement panel in the DOM after its in-page
   * navigation. Reading the whole document therefore returned every panel's
   * segments one after another, which saved the transcript twice.
   */
  function findSegmentList() {
    const lists = Array.from(
      document.querySelectorAll('ytd-transcript-segment-list-renderer')
    );
    if (lists.length === 0) return null;

    // A panel left over from an earlier video is still in the DOM but hidden.
    const onScreen = lists.filter((list) => list.offsetParent !== null);
    const candidates = onScreen.length > 0 ? onScreen : lists;

    // The panel for the current video is the last one YouTube appended.
    return candidates[candidates.length - 1];
  }

  function readSegments() {
    const list = findSegmentList();
    if (!list) return [];

    const nodes = list.querySelectorAll('ytd-transcript-segment-renderer');
    const segments = [];
    nodes.forEach((node) => {
      const textNode = node.querySelector('.segment-text');
      if (!textNode) return;
      const text = textNode.textContent.replace(/\s+/g, ' ').trim();
      if (!text) return;

      const stampNode = node.querySelector('.segment-timestamp');
      const stamp = stampNode ? stampNode.textContent.trim() : '';
      segments.push({ start: parseTimestamp(stamp), text: text });
    });
    return segments;
  }

  function findTranscriptButton() {
    // Structural selector first: it does not depend on the interface language.
    const inDescription = document.querySelector(
      'ytd-video-description-transcript-section-renderer button'
    );
    if (inDescription) return inDescription;

    const buttons = document.querySelectorAll('button');
    for (const button of buttons) {
      const label = (button.getAttribute('aria-label') || button.textContent || '').toLowerCase();
      if (label.includes('transcript') || label.includes('přepis') || label.includes('transkript')) {
        return button;
      }
    }
    return null;
  }

  let segments = readSegments();
  if (segments.length > 0) {
    return { ok: true, segments: segments, source: 'panel' };
  }

  // The transcript button lives inside the collapsed description, so expand it first.
  const expandButton = document.querySelector('tp-yt-paper-button#expand, #description-inline-expander #expand');
  if (expandButton) {
    expandButton.click();
    await sleep(600);
  }

  const transcriptButton = findTranscriptButton();
  if (!transcriptButton) {
    return { ok: false, error: 'No transcript is available for this video.' };
  }
  transcriptButton.click();

  // The panel loads asynchronously; poll for up to ~8 seconds.
  for (let attempt = 0; attempt < 16; attempt++) {
    await sleep(500);
    segments = readSegments();
    if (segments.length > 0) {
      return { ok: true, segments: segments, source: 'panel' };
    }
  }
  return { ok: false, error: 'The transcript panel did not load in time.' };
}

/* ------------------------------------------------------------------ */
/* Markdown building                                                   */
/* ------------------------------------------------------------------ */

/**
 * YouTube's caption text sometimes still contains HTML entities.
 */
function decodeHtmlEntities(text) {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ');
}

/**
 * 75 -> "1:15", 3675 -> "1:01:15"
 */
function formatTimestamp(totalSeconds) {
  const wholeSeconds = Math.floor(totalSeconds);
  const seconds = wholeSeconds % 60;
  const minutes = Math.floor(wholeSeconds / 60) % 60;
  const hours = Math.floor(wholeSeconds / 3600);

  const paddedSeconds = String(seconds).padStart(2, '0');
  if (hours > 0) {
    const paddedMinutes = String(minutes).padStart(2, '0');
    return hours + ':' + paddedMinutes + ':' + paddedSeconds;
  }
  return minutes + ':' + paddedSeconds;
}

/**
 * Guards against a source handing back the same transcript more than once.
 *
 * Caption times only ever move forward, so a segment that starts well before
 * the one in front of it means the stream has looped back to the beginning;
 * everything from that point on repeats what we already have.
 *
 * The tolerance is there so one caption arriving a fraction of a second out of
 * order does not truncate an otherwise good transcript.
 */
function dropRepeatedPass(segments) {
  for (let index = 1; index < segments.length; index++) {
    const jumpedBack = segments[index - 1].start - segments[index].start;
    if (jumpedBack > RESTART_BACKWARD_SECONDS) {
      return segments.slice(0, index);
    }
  }
  return segments;
}

/**
 * Merges the many tiny caption segments into readable chunks.
 * Each chunk keeps the start time of its first segment.
 */
function groupSegments(segments) {
  const chunks = [];
  let current = null;

  for (const segment of segments) {
    const text = decodeHtmlEntities(segment.text);

    if (current === null) {
      current = { start: segment.start, text: text };
      continue;
    }

    const isTooLong = current.text.length + text.length > CHUNK_MAX_CHARS;
    const isTooOld = segment.start - current.start > CHUNK_MAX_SECONDS;
    // Time running backwards always starts a new chunk. Without this the
    // subtraction above goes negative and the seam is silently glued together.
    const isOutOfOrder = segment.start < current.start;
    if (isTooLong || isTooOld || isOutOfOrder) {
      chunks.push(current);
      current = { start: segment.start, text: text };
      continue;
    }

    current.text = current.text + ' ' + text;
  }

  if (current !== null) {
    chunks.push(current);
  }
  return chunks;
}

/**
 * Builds the whole .md file: a title, a metadata list, then the transcript.
 */
function buildMarkdown(videoInfo, trackLabel, segments, includeTimestamps) {
  const lines = [];
  lines.push('# ' + videoInfo.title);
  lines.push('');

  if (videoInfo.author) {
    lines.push('- **Channel:** ' + videoInfo.author);
  }
  lines.push('- **URL:** ' + videoInfo.pageUrl);
  if (videoInfo.lengthSeconds > 0) {
    lines.push('- **Duration:** ' + formatTimestamp(videoInfo.lengthSeconds));
  }
  if (trackLabel) {
    lines.push('- **Transcript:** ' + trackLabel);
  }
  lines.push('- **Saved:** ' + new Date().toISOString().slice(0, 10));
  lines.push('');
  lines.push('---');
  lines.push('');

  const chunks = groupSegments(segments);
  for (const chunk of chunks) {
    if (includeTimestamps) {
      lines.push('**[' + formatTimestamp(chunk.start) + ']** ' + chunk.text);
    } else {
      lines.push(chunk.text);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Turns a video title into something the filesystem accepts.
 * Chrome rejects path separators, reserved characters and leading/trailing dots.
 */
function toSafeFilename(title) {
  let name = title.replace(/[\\/:*?"<>|]/g, '-');
  name = name.replace(/[\x00-\x1f\x7f]/g, ''); // control characters
  name = name.replace(/\s+/g, ' ').trim();
  name = name.replace(/^\.+/, '').replace(/\.+$/, '').trim();
  name = name.slice(0, 120).trim();

  if (!name) {
    return 'youtube-transcript';
  }
  return name;
}

/* ------------------------------------------------------------------ */
/* Orchestration                                                       */
/* ------------------------------------------------------------------ */

async function runInPage(tabId, injectedFunction, functionArguments, world) {
  const results = await chrome.scripting.executeScript({
    target: { tabId: tabId },
    world: world,
    func: injectedFunction,
    args: functionArguments || []
  });
  return results[0].result;
}

async function readVideoInfo(tabId) {
  return runInPage(tabId, pageReadVideoInfo, [], 'MAIN');
}

/**
 * Picks the track to use when the caller did not choose one:
 * a human-made track wins over an auto-generated one.
 */
function pickDefaultTrack(tracks) {
  const manualTrack = tracks.find((track) => !track.isAutoGenerated);
  if (manualTrack) return manualTrack;
  return tracks[0] || null;
}

/**
 * The full job: read the page, get the transcript, write the file.
 * Returns { ok: true, filename } or { ok: false, error }.
 */
async function saveTranscript(tabId, options) {
  const settings = options || {};

  const videoInfo = await readVideoInfo(tabId);
  if (!videoInfo || !videoInfo.ok) {
    return { ok: false, error: (videoInfo && videoInfo.error) || 'Not a YouTube video page.' };
  }

  let trackLabel = settings.trackLabel || '';
  let transcript = null;

  let trackUrl = settings.trackUrl;
  if (!trackUrl) {
    const defaultTrack = pickDefaultTrack(videoInfo.tracks);
    if (defaultTrack) {
      trackUrl = defaultTrack.url;
      trackLabel = defaultTrack.label + (defaultTrack.isAutoGenerated ? ' (auto-generated)' : '');
    }
  }

  if (trackUrl) {
    transcript = await runInPage(tabId, pageFetchCaptionTrack, [trackUrl], 'MAIN');
  }

  // No caption track, or YouTube refused the download: read the on-page panel instead.
  if (!transcript || !transcript.ok) {
    transcript = await runInPage(tabId, pageScrapeTranscriptPanel, [], 'ISOLATED');
    if (transcript && transcript.ok) {
      trackLabel = trackLabel || 'from transcript panel';
    }
  }

  if (!transcript || !transcript.ok) {
    return { ok: false, error: (transcript && transcript.error) || 'No transcript found for this video.' };
  }

  // Both sources can hand back the same transcript twice, so clean the list once
  // here: the file and the "N caption lines" message then agree with each other.
  const segments = dropRepeatedPass(transcript.segments);

  const includeTimestamps = settings.includeTimestamps !== false;
  const markdown = buildMarkdown(videoInfo, trackLabel, segments, includeTimestamps);

  const filename = toSafeFilename(videoInfo.title) + '.md';
  const downloadPath = DOWNLOAD_SUBFOLDER ? DOWNLOAD_SUBFOLDER + '/' + filename : filename;
  const dataUrl = 'data:text/markdown;charset=utf-8,' + encodeURIComponent(markdown);

  await chrome.downloads.download({
    url: dataUrl,
    filename: downloadPath,
    saveAs: false
  });

  return { ok: true, filename: downloadPath, segmentCount: segments.length };
}

/* ------------------------------------------------------------------ */
/* Entry points                                                        */
/* ------------------------------------------------------------------ */

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'GET_INFO') {
    readVideoInfo(message.tabId)
      .then(sendResponse)
      .catch((error) => sendResponse({ ok: false, error: error.message }));
    return true; // keeps the message channel open for the async reply
  }

  if (message.type === 'SAVE') {
    saveTranscript(message.tabId, message.options)
      .then(sendResponse)
      .catch((error) => sendResponse({ ok: false, error: error.message }));
    return true;
  }

  return false;
});

chrome.commands.onCommand.addListener(async (command) => {
  if (command !== 'save-transcript') return;

  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (!tab || !tab.url || !tab.url.includes('youtube.com/watch')) return;

  const stored = await chrome.storage.sync.get({ includeTimestamps: true });
  await saveTranscript(tab.id, { includeTimestamps: stored.includeTimestamps });
});
