/**
 * Popup UI. It owns no logic of its own: it asks the service worker for the
 * video info, shows it, and asks the service worker to save the file.
 */

const titleElement = document.getElementById('videoTitle');
const channelElement = document.getElementById('videoChannel');
const controlsElement = document.getElementById('controls');
const trackSelect = document.getElementById('trackSelect');
const timestampsCheckbox = document.getElementById('includeTimestamps');
const saveButton = document.getElementById('saveButton');
const statusElement = document.getElementById('status');

let activeTabId = null;
let availableTracks = [];

function showStatus(message, isError) {
  statusElement.textContent = message;
  statusElement.className = isError ? 'error' : '';
}

function sendToBackground(message) {
  return chrome.runtime.sendMessage(message);
}

function fillTrackDropdown(tracks) {
  trackSelect.innerHTML = '';

  if (tracks.length === 0) {
    const option = document.createElement('option');
    option.textContent = 'Read from the transcript panel';
    option.value = '';
    trackSelect.appendChild(option);
    return;
  }

  tracks.forEach((track, index) => {
    const option = document.createElement('option');
    option.value = String(index);
    option.textContent = track.label + (track.isAutoGenerated ? ' (auto-generated)' : '');
    trackSelect.appendChild(option);
  });

  // Prefer a human-made track over YouTube's automatic one.
  const manualIndex = tracks.findIndex((track) => !track.isAutoGenerated);
  if (manualIndex >= 0) {
    trackSelect.value = String(manualIndex);
  }
}

async function loadVideoInfo() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

  if (!tab || !tab.url || !tab.url.includes('youtube.com/watch')) {
    titleElement.textContent = 'Open a YouTube video first.';
    return;
  }
  activeTabId = tab.id;

  const info = await sendToBackground({ type: 'GET_INFO', tabId: activeTabId });
  if (!info || !info.ok) {
    titleElement.textContent = 'Could not read this page.';
    showStatus((info && info.error) || 'Try reloading the video page.', true);
    return;
  }

  titleElement.textContent = info.title;
  channelElement.textContent = info.author;
  availableTracks = info.tracks || [];
  fillTrackDropdown(availableTracks);
  controlsElement.classList.remove('hidden');

  if (availableTracks.length === 0) {
    showStatus('No caption track found — the transcript panel will be used instead.', false);
  }
}

async function onSaveClicked() {
  saveButton.disabled = true;
  showStatus('Fetching transcript…', false);

  const selectedTrack = availableTracks[Number(trackSelect.value)];
  const includeTimestamps = timestampsCheckbox.checked;
  await chrome.storage.sync.set({ includeTimestamps: includeTimestamps });

  const result = await sendToBackground({
    type: 'SAVE',
    tabId: activeTabId,
    options: {
      trackUrl: selectedTrack ? selectedTrack.url : '',
      trackLabel: selectedTrack ? selectedTrack.label : '',
      includeTimestamps: includeTimestamps
    }
  });

  saveButton.disabled = false;

  if (!result || !result.ok) {
    showStatus((result && result.error) || 'Something went wrong.', true);
    return;
  }
  showStatus('Saved ' + result.filename + ' (' + result.segmentCount + ' caption lines).', false);
}

saveButton.addEventListener('click', onSaveClicked);

chrome.storage.sync.get({ includeTimestamps: true }).then((stored) => {
  timestampsCheckbox.checked = stored.includeTimestamps;
});

loadVideoInfo();
